// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-19BHK0m5QW3ISM83iZ40LnHygHQhi24',
    appId: '1:995979342290:web:c5e7ad562333189878180b',
    messagingSenderId: '995979342290',
    projectId: 'cropconnect-ba639',
    authDomain: 'cropconnect-ba639.firebaseapp.com',
    storageBucket: 'cropconnect-ba639.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_GW_D3_cn3VVN0jS-9KzWqfdZJ1uMpWQ',
    appId: '1:995979342290:android:2c89bddc85ea435e78180b',
    messagingSenderId: '995979342290',
    projectId: 'cropconnect-ba639',
    storageBucket: 'cropconnect-ba639.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChB7LJN56yXhLyVQ9Og7W3PC1iEGHymHA',
    appId: '1:995979342290:ios:998ac9a4b382fc4b78180b',
    messagingSenderId: '995979342290',
    projectId: 'cropconnect-ba639',
    storageBucket: 'cropconnect-ba639.firebasestorage.app',
    iosBundleId: 'com.example.cropconnect',
  );

}